version: '3'
services:
    db:
        image: 'postgres:latest'
        container_name: quickstore-db
        volumes:
            - ./db:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
        ports:
            - "5432:5432"
 


